"""GDS Assembly — reads Phase 2/3/4 JSON outputs, instantiates PCells + geometry.

Run with: klayout -n sg13g2 -zz -r assemble_gds.py

Inputs:
  placement.json  — device positions (Phase 2)
  ties.json       — tie cell geometry (Phase 3)
  routing.json    — access points + power + signals (Phase 4)

Output:
  $GDS_OUTPUT (default layout/output/ptat_vco.gds)
"""

import os
import sys
import json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__ if '__file__' in dir() else '.')))

import pya
import klayout.db

from atk.pdk import (
    METAL1, METAL2, METAL3, VIA1, VIA2,
    METAL1_PIN, METAL2_PIN, METAL3_PIN,
    METAL1_LBL, METAL2_LBL, METAL3_LBL,
    TOPMETAL1, TOPMETAL1_PIN,
    ACTIV, GATPOLY, CONT, NWELL, PSD,
    UM, M1_SIG_W, M1_THIN, M2_SIG_W, M3_PWR_W,
    VIA1_SZ, VIA1_PAD, VIA1_PAD_M1, VIA2_SZ, VIA2_PAD,
    M2_MIN_S, M1_MIN_S, M3_MIN_S,
    GATE_POLY_EXT, CNT_D_ENC,
    s5,
)
from atk.route.maze_router import M1_LYR, M2_LYR
from atk.device import load_device_lib, get_pcell_params, get_ng2_gate_data, get_sd_strips
from atk.verify.pcell_xray import load_gate_info
from atk.paths import DEVICE_LIB_JSON

LIB_NAME = 'SG13_dev'

# Device data loaded from device_lib.json (auto-generated by probe_pcells_v2.py)
_device_lib = load_device_lib(DEVICE_LIB_JSON)
DEVICES = {dt: get_pcell_params(_device_lib, dt) for dt in _device_lib}
_gate_info = load_gate_info(DEVICE_LIB_JSON)


# ═══════════════════════════════════════════════════
# Drawing helpers
# ═══════════════════════════════════════════════════

def hbar(cell, li, x1, x2, y, w):
    hw = w // 2
    cell.shapes(li).insert(klayout.db.Box(min(x1, x2), y - hw, max(x1, x2), y + hw))


def vbar(cell, li, x, y1, y2, w):
    hw = w // 2
    cell.shapes(li).insert(klayout.db.Box(x - hw, min(y1, y2), x + hw, max(y1, y2)))


def wire(cell, li, pts, w):
    kpts = [klayout.db.Point(int(x), int(y)) for x, y in pts]
    cell.shapes(li).insert(klayout.db.Path(kpts, int(w)))


def via1(cell, li_v, li_m1, li_m2, x, y, m1_pad=None):
    hs = VIA1_SZ // 2
    hp_m1 = (m1_pad if m1_pad is not None else VIA1_PAD) // 2
    hp_m2 = VIA1_PAD // 2
    cell.shapes(li_v).insert(klayout.db.Box(x - hs, y - hs, x + hs, y + hs))
    cell.shapes(li_m1).insert(klayout.db.Box(x - hp_m1, y - hp_m1, x + hp_m1, y + hp_m1))
    cell.shapes(li_m2).insert(klayout.db.Box(x - hp_m2, y - hp_m2, x + hp_m2, y + hp_m2))


def via2(cell, li_v2, li_m2, li_m3, x, y):
    hs = VIA2_SZ // 2
    hp = VIA2_PAD // 2
    cell.shapes(li_v2).insert(klayout.db.Box(x - hs, y - hs, x + hs, y + hs))
    cell.shapes(li_m2).insert(klayout.db.Box(x - hp, y - hp, x + hp, y + hp))
    cell.shapes(li_m3).insert(klayout.db.Box(x - hp, y - hp, x + hp, y + hp))


def draw_rect(cell, li, rect):
    """Draw [x1, y1, x2, y2] nm rect."""
    cell.shapes(li).insert(klayout.db.Box(rect[0], rect[1], rect[2], rect[3]))


def _near_any(x, y, via_set, threshold):
    """Check if (x, y) is within threshold of any point in via_set."""
    for vx, vy in via_set:
        if abs(x - vx) <= threshold and abs(y - vy) <= threshold:
            return True
    return False


def draw_segments(cell, li_m1, li_m2, li_v1, segments, w,
                   drawn_vias=None):
    """Draw route segments.

    When drawn_vias is provided, skip Via1+pads at positions that are
    within VIA1_PAD//2 of an already-drawn via (access point).
    Math guarantee: grid quantization error < MAZE_GRID/2 = 175nm
                    < VIA1_PAD/2 = 240nm, so AP pad always covers
                    the grid-snapped wire endpoint.
    """
    skip_threshold = VIA1_PAD // 2   # = 240nm — derived from pdk.py
    for seg in segments:
        x1, y1, x2, y2, layer = seg[0], seg[1], seg[2], seg[3], seg[4]
        if layer == -1:
            if drawn_vias is not None and _near_any(x1, y1, drawn_vias,
                                                     skip_threshold):
                continue
            via1(cell, li_v1, li_m1, li_m2, x1, y1, m1_pad=VIA1_PAD_M1)
            if drawn_vias is not None:
                drawn_vias.add((x1, y1))
        elif layer == M1_LYR:
            if x1 == x2:
                vbar(cell, li_m1, x1, y1, y2, w)
            elif y1 == y2:
                hbar(cell, li_m1, x1, x2, y1, w)
            else:
                wire(cell, li_m1, [(x1, y1), (x2, y2)], w)
        elif layer == M2_LYR:
            if x1 == x2:
                vbar(cell, li_m2, x1, y1, y2, w)
            elif y1 == y2:
                hbar(cell, li_m2, x1, x2, y1, w)
            else:
                wire(cell, li_m2, [(x1, y1), (x2, y2)], w)


# ═══════════════════════════════════════════════════
# JSON loaders — all paths from atk.paths (single source of truth)
# ═══════════════════════════════════════════════════

# KLayout's -r runner may not set __file__, so resolve paths robustly.
try:
    from atk.paths import PLACEMENT_JSON as _PL, TIES_JSON as _TI, ROUTING_JSON as _RO
except ImportError:
    import sys as _sys
    _sys.path.insert(0, os.path.dirname(os.path.abspath(
        __file__ if '__file__' in dir() else '.')))
    from atk.paths import PLACEMENT_JSON as _PL, TIES_JSON as _TI, ROUTING_JSON as _RO


def load_jsons():
    with open(_PL) as f:
        placement = json.load(f)
    with open(_TI) as f:
        ties = json.load(f)
    with open(_RO) as f:
        routing = json.load(f)

    print(f'  Loaded: {_PL}')
    print(f'  Loaded: {_TI}')
    print(f'  Loaded: {_RO}')
    return placement, ties, routing


# ═══════════════════════════════════════════════════
# Layer name→(layer, datatype) parser for ties.json
# ═══════════════════════════════════════════════════

# ties.json uses keys like "Activ_1_0", "Cont_6_0", "M1_8_0", "NW_31_0", "pSD_14_0"
_TIE_LAYER_MAP = {
    'Activ': ACTIV,
    'Cont': CONT,
    'M1': METAL1,
    'NW': NWELL,
    'pSD': PSD,
}


def _parse_tie_layer(key):
    """Parse 'Activ_1_0' → (1, 0)."""
    parts = key.rsplit('_', 2)
    if len(parts) == 3:
        return (int(parts[1]), int(parts[2]))
    # Fallback: try name lookup
    name = parts[0]
    return _TIE_LAYER_MAP.get(name, None)


# ═══════════════════════════════════════════════════
# Power drop M2 fill helpers
# ═══════════════════════════════════════════════════

def _fill_via_m1_corners(cell, li_m1, routing, gate_cont_m1=None):
    """Fill M1 corner notches between via M1 pads and M1 wire segments.

    When a via1 and an M1 wire bar are in the same net but not directly
    connected (e.g., via → hbar → vbar), the via M1 pad and wire bar
    may have a small gap (~15nm) that violates M1.b (180nm min notch).

    Also checks access point via pads and gate contact M1 pads against
    routing wire segments on the same net, to fix notches.
    """
    hp_m1 = VIA1_PAD_M1 // 2  # 185
    hw = M1_SIG_W // 2         # 150

    # Build pin→net map for access point matching
    _pin_to_net = {}
    for route_dict in [routing.get('signal_routes', {}), routing.get('pre_routes', {})]:
        for net_name, rd in route_dict.items():
            for pin_key in rd.get('pins', []):
                _pin_to_net[pin_key] = net_name

    # Collect access point M1 pads and m1_stubs per net
    _ap_m1_per_net = {}
    for key, ap in routing.get('access_points', {}).items():
        net = _pin_to_net.get(key)
        if not net:
            continue
        vp = ap.get('via_pad')
        if vp and 'm1' in vp:
            _ap_m1_per_net.setdefault(net, []).append(vp['m1'])
        stub = ap.get('m1_stub')
        if stub:
            _ap_m1_per_net.setdefault(net, []).append(stub)

    # Add gate contact M1 pads (drawn in section 1c)
    if gate_cont_m1:
        for pin_key, rect in gate_cont_m1.items():
            net = _pin_to_net.get(pin_key)
            if net:
                _ap_m1_per_net.setdefault(net, []).append(rect)

    fill_count = 0
    for route_dict in [routing.get('signal_routes', {}), routing.get('pre_routes', {})]:
        for _net, rd in route_dict.items():
            segs = rd.get('segments', [])
            # Collect all vias and M1 wire boxes in this net
            vias_m1 = []
            wires_m1 = []
            for seg in segs:
                if len(seg) < 5:
                    continue
                x1, y1, x2, y2, layer = seg
                if layer == -1:  # via
                    vias_m1.append([x1 - hp_m1, y1 - hp_m1, x1 + hp_m1, y1 + hp_m1])
                elif layer == 0:  # M1 wire
                    if x1 == x2:  # vertical
                        wires_m1.append([x1 - hw, min(y1, y2), x1 + hw, max(y1, y2)])
                    elif y1 == y2:  # horizontal
                        wires_m1.append([min(x1, x2) - hw, y1 - hw,
                                         max(x1, x2) + hw, y1 + hw])

            # Add access point M1 pads for this net
            ap_pads = _ap_m1_per_net.get(_net, [])
            all_m1_pads = vias_m1 + [list(p) for p in ap_pads]

            # Check all pad-wire pairs for notch gaps AND overlap notches
            for vm in all_m1_pads:
                for wm in wires_m1:
                    x_gap = max(vm[0] - wm[2], wm[0] - vm[2])
                    y_gap = max(vm[1] - wm[3], wm[1] - vm[3])
                    if 0 < x_gap < M1_MIN_S and y_gap < 0:
                        # Separated in X, overlapping in Y → fill X gap
                        fx1 = min(vm[0], wm[0])
                        fx2 = max(vm[2], wm[2])
                        fy1 = max(vm[1], wm[1])
                        fy2 = min(vm[3], wm[3])
                        if fy1 < fy2:
                            cell.shapes(li_m1).insert(klayout.db.Box(fx1, fy1, fx2, fy2))
                            fill_count += 1
                    elif 0 < y_gap < M1_MIN_S and x_gap < 0:
                        # Separated in Y, overlapping in X → fill Y gap
                        fx1 = max(vm[0], wm[0])
                        fx2 = min(vm[2], wm[2])
                        fy1 = min(vm[1], wm[1])
                        fy2 = max(vm[3], wm[3])
                        if fx1 < fx2:
                            cell.shapes(li_m1).insert(klayout.db.Box(fx1, fy1, fx2, fy2))
                            fill_count += 1
                    # Note: overlap case (x_gap < 0, y_gap < 0) is NOT filled.
                    # Overlapping same-net M1 shapes with width steps create
                    # M1.b notch violations (step < 180nm), but filling the
                    # overlap region extends M1 into areas near other nets.
    if fill_count:
        print(f'    Filled {fill_count} M1 via/pad corner notches')


def _fill_via_ap_m2_gaps(cell, li_m2, routing):
    """Fill M2 gaps between routing vias and nearby access point M2 pads.

    When a signal route places a via close to (but not overlapping) an access
    point's M2 pad, the gap can violate M2.b (210nm min spacing).  This
    function detects such gaps and draws a bridging M2 rectangle.
    """
    hp_m2 = VIA1_PAD // 2  # via M2 pad half-size = 240nm

    # Collect all routing via positions from signal + pre-route segments
    via_positions = []
    for route_dict in [routing.get('signal_routes', {}), routing.get('pre_routes', {})]:
        for _net, rd in route_dict.items():
            for seg in rd.get('segments', []):
                if len(seg) >= 5 and seg[4] == -1:  # via down marker
                    via_positions.append((seg[0], seg[1]))

    # Collect all access point M2 pads
    ap_m2_pads = []
    for _key, ap in routing.get('access_points', {}).items():
        vp = ap.get('via_pad')
        if vp and 'm2' in vp:
            ap_m2_pads.append(vp['m2'])

    fill_count = 0
    for vx, vy in via_positions:
        via_m2 = [vx - hp_m2, vy - hp_m2, vx + hp_m2, vy + hp_m2]
        for pad in ap_m2_pads:
            # Check if close but not overlapping (gap < M2_MIN_S)
            x_gap = max(via_m2[0] - pad[2], pad[0] - via_m2[2])
            y_gap = max(via_m2[1] - pad[3], pad[1] - via_m2[3])
            if x_gap > 0 and x_gap < M2_MIN_S and y_gap < 0:
                # X gap < M2.b with Y overlap → fill
                fill_x1 = min(via_m2[0], pad[0])
                fill_x2 = max(via_m2[2], pad[2])
                fill_y1 = max(via_m2[1], pad[1])
                fill_y2 = min(via_m2[3], pad[3])
                if fill_y1 < fill_y2:
                    cell.shapes(li_m2).insert(
                        klayout.db.Box(fill_x1, fill_y1, fill_x2, fill_y2))
                    fill_count += 1
            elif y_gap > 0 and y_gap < M2_MIN_S and x_gap < 0:
                # Y gap < M2.b with X overlap → fill
                fill_x1 = max(via_m2[0], pad[0])
                fill_x2 = min(via_m2[2], pad[2])
                fill_y1 = min(via_m2[1], pad[1])
                fill_y2 = max(via_m2[3], pad[3])
                if fill_x1 < fill_x2:
                    cell.shapes(li_m2).insert(
                        klayout.db.Box(fill_x1, fill_y1, fill_x2, fill_y2))
                    fill_count += 1
    if fill_count:
        print(f'    Filled {fill_count} M2 via-to-pad gaps')


def _fill_vbar_to_pad(cell, li_m2, vb, drop, routing):
    """Draw M2 fill rectangle bridging power vbar to access point M2 pad.

    The vbar X is offset from the pin (due to jog routing), and the M2 pad is
    centered on the pin.  Without a fill, there can be a ~30nm gap between the
    vbar right/left edge and the pad edge, violating M2.b (210nm min spacing).
    """
    inst_pin = f"{drop['inst']}.{drop['pin']}"
    ap = routing.get('access_points', {}).get(inst_pin)
    if not ap or not ap.get('via_pad') or 'm2' not in ap['via_pad']:
        return
    m2_pad = ap['via_pad']['m2']  # [x1, y1, x2, y2]
    # vbar: vertical bar at vb[0] with width M2_SIG_W
    vbar_hw = M2_SIG_W // 2
    vbar_x1 = vb[0] - vbar_hw
    vbar_x2 = vb[0] + vbar_hw
    # Fill rectangle: union of vbar X range and pad X range at pad Y range
    fill_x1 = min(vbar_x1, m2_pad[0])
    fill_x2 = max(vbar_x2, m2_pad[2])
    # Y range: intersection of vbar Y range and pad Y range
    vbar_y1 = min(vb[1], vb[3])
    vbar_y2 = max(vb[1], vb[3])
    fill_y1 = max(vbar_y1, m2_pad[1])
    fill_y2 = min(vbar_y2, m2_pad[3])
    if fill_y1 < fill_y2:
        cell.shapes(li_m2).insert(klayout.db.Box(fill_x1, fill_y1, fill_x2, fill_y2))


# ═══════════════════════════════════════════════════
# M2 power/signal collision check
# ═══════════════════════════════════════════════════

def _check_m2_power_signal_collision(routing):
    """Abort if any signal M2 wire overlaps a power M2 pad.

    Checks all signal_route M2 segments against all power drop M2 shapes
    (vbars, jogs) and access point M2 pads for power pins.
    """
    from atk.route.access import _DEVICES as _ACC_DEV
    import json

    # Load netlist for pin→net mapping
    here = os.path.dirname(os.path.abspath(__file__ if '__file__' in dir() else '.'))
    netlist_path = os.path.join(here, 'netlist.json')
    if not os.path.exists(netlist_path):
        netlist_path = '/private/tmp/analog-trial/layout/netlist.json'
    with open(netlist_path) as f:
        netlist = json.load(f)

    pin_net = {}
    for ne in netlist['nets']:
        for pin in ne['pins']:
            pin_net[pin] = ne['name']

    power_nets = {'vdd', 'gnd', 'vdd_vco'}
    hw = M2_SIG_W // 2

    # Collect power M2 rectangles (from access points of power pins)
    power_m2 = []
    for key, ap in routing.get('access_points', {}).items():
        net = pin_net.get(key, '')
        if net not in power_nets:
            continue
        vp = ap.get('via_pad', {})
        if 'm2' in vp:
            power_m2.append((vp['m2'], key, net))

    # Collect power M2 from drops (vbars, jogs)
    for drop in routing.get('power', {}).get('drops', []):
        vb = drop.get('m2_vbar')
        if vb:
            vb_rect = [vb[0] - hw, min(vb[1], vb[3]), vb[0] + hw, max(vb[1], vb[3])]
            power_m2.append((vb_rect, f"{drop['inst']}.{drop['pin']}", drop['net']))
        jog = drop.get('m2_jog')
        if jog:
            jhw = VIA1_PAD // 2
            jog_rect = [min(jog[0], jog[2]), jog[1] - jhw, max(jog[0], jog[2]), jog[1] + jhw]
            power_m2.append((jog_rect, f"{drop['inst']}.{drop['pin']}_jog", drop['net']))

    # Check signal M2 segments against power M2
    collisions = []
    for sig_net, route in routing.get('signal_routes', {}).items():
        for seg in route.get('segments', []):
            if len(seg) < 5 or seg[4] != 1:  # M2 only
                continue
            x1, y1, x2, y2 = seg[0], seg[1], seg[2], seg[3]
            sx1 = min(x1, x2) - hw
            sy1 = min(y1, y2) - hw
            sx2 = max(x1, x2) + hw
            sy2 = max(y1, y2) + hw
            for prect, pkey, pnet in power_m2:
                # Check overlap
                if sx1 < prect[2] and sx2 > prect[0] and sy1 < prect[3] and sy2 > prect[1]:
                    collisions.append((sig_net, pkey, pnet,
                                       (sx1, sy1, sx2, sy2), prect))

    if collisions:
        print(f'\n  *** M2 COLLISION: {len(collisions)} signal/power overlaps ***')
        for sig, pkey, pnet, srect, prect in collisions:
            print(f'    {sig} M2 <-> {pkey} ({pnet}) M2')
            print(f'      signal: ({srect[0]},{srect[1]})-({srect[2]},{srect[3]})')
            print(f'      power:  ({prect[0]},{prect[1]})-({prect[2]},{prect[3]})')
        raise RuntimeError(f'M2 power/signal collision detected: {len(collisions)} overlaps')


# ═══════════════════════════════════════════════════
# Multi-rail bridge helper
# ═══════════════════════════════════════════════════

def _draw_rail_bridges(cell, li_m2, li_v2, li_m3, rails, m2_signal_segs):
    """Connect same-net M3 rails with M2 underpass bridges.

    For each pair of same-net rails, draws:
    - Via2 on each rail at a shared X position
    - M2 vertical bar between the two Via2 points

    X position chosen at the left margin to avoid M2 signal conflicts.
    """
    from collections import defaultdict

    # Group rails by net
    net_rails = defaultdict(list)
    for rail_id, rail in rails.items():
        net = rail.get('net', rail_id)
        net_rails[net].append((rail_id, rail))

    bridge_count = 0
    # Assign distinct X positions per net to avoid M2 collision between bridges
    net_idx = 0
    for net, rail_list in sorted(net_rails.items()):
        if len(rail_list) < 2:
            continue

        # Sort by Y
        rail_list.sort(key=lambda r: r[1]['y'])

        # Bridge each adjacent pair
        for i in range(len(rail_list) - 1):
            rid1, r1 = rail_list[i]
            rid2, r2 = rail_list[i + 1]

            y1 = r1['y']
            y2 = r2['y']

            # Choose X: offset each net by 2µm to avoid inter-bridge M2 shorts
            # First net at left margin, next at left+2µm, etc.
            base_x = r1['x1'] + 1500
            bridge_x = base_x + net_idx * 2000

            # Check for M2 signal conflicts at this X column
            hp = VIA2_PAD // 2
            has_conflict = False
            for sx1, sy1, sx2, sy2 in m2_signal_segs:
                sw = M2_SIG_W // 2
                # Check if M2 signal overlaps our bridge column
                seg_x1 = min(sx1, sx2) - sw
                seg_x2 = max(sx1, sx2) + sw
                seg_y1 = min(sy1, sy2)
                seg_y2 = max(sy1, sy2)
                if (bridge_x - hp < seg_x2 and bridge_x + hp > seg_x1 and
                        seg_y1 < y2 and seg_y2 > y1):
                    has_conflict = True
                    break

            if has_conflict:
                # Shift to right margin
                bridge_x = r1['x2'] - 1500 - net_idx * 2000

            # Draw Via2 at both rails
            via2(cell, li_v2, li_m2, li_m3, bridge_x, y1)
            via2(cell, li_v2, li_m2, li_m3, bridge_x, y2)

            # Draw M2 vbar between them
            vbar(cell, li_m2, bridge_x, y1, y2, VIA2_PAD)

            bridge_count += 1
            print(f'    Bridge {rid1} <-> {rid2} ({net}): '
                  f'x={bridge_x / 1000:.1f}µm, '
                  f'y={y1 / 1000:.1f}-{y2 / 1000:.1f}µm')

        net_idx += 1

    print(f'  Drew {bridge_count} multi-rail bridges')


# ═══════════════════════════════════════════════════
# NWell bridge helper
# ═══════════════════════════════════════════════════

def _add_nwell_bridge(cell, layout, placement):
    """Add NWell bridge between MBp1 and MBp2 to avoid NW.b1 PWell width violation.

    Reads actual PCell NWell shapes from the layout to determine precise Y range,
    then draws a bridging rectangle at the Y intersection.
    """
    li_nw = layout.layer(*NWELL)

    # MBp1 and MBp2 placement bounding boxes (nm)
    mbp1 = placement['instances'].get('MBp1')
    mbp2 = placement['instances'].get('MBp2')
    if not mbp1 or not mbp2:
        return

    mbp1_x1 = s5(mbp1['x_um'])
    mbp1_x2 = mbp1_x1 + s5(mbp1['w_um'])
    mbp2_x1 = s5(mbp2['x_um'])
    mbp2_x2 = mbp2_x1 + s5(mbp2['w_um'])

    # Scan NWell shapes in the layout to find actual PCell NWell Y extents
    # for each device region
    mbp1_nw_ymin, mbp1_nw_ymax = None, None
    mbp1_nw_xmax = None
    mbp2_nw_ymin, mbp2_nw_ymax = None, None
    mbp2_nw_xmin = None

    for si in cell.begin_shapes_rec(li_nw):
        box = si.shape().bbox().transformed(si.trans())
        cx = (box.left + box.right) // 2
        # Attribute NWell shape to MBp1 or MBp2 based on X center
        if mbp1_x1 - 500 <= cx <= mbp1_x2 + 500:
            if mbp1_nw_ymin is None or box.bottom < mbp1_nw_ymin:
                mbp1_nw_ymin = box.bottom
            if mbp1_nw_ymax is None or box.top > mbp1_nw_ymax:
                mbp1_nw_ymax = box.top
            if mbp1_nw_xmax is None or box.right > mbp1_nw_xmax:
                mbp1_nw_xmax = box.right
        if mbp2_x1 - 500 <= cx <= mbp2_x2 + 500:
            if mbp2_nw_ymin is None or box.bottom < mbp2_nw_ymin:
                mbp2_nw_ymin = box.bottom
            if mbp2_nw_ymax is None or box.top > mbp2_nw_ymax:
                mbp2_nw_ymax = box.top
            if mbp2_nw_xmin is None or box.left < mbp2_nw_xmin:
                mbp2_nw_xmin = box.left

    if any(v is None for v in [mbp1_nw_ymin, mbp1_nw_ymax, mbp1_nw_xmax,
                                mbp2_nw_ymin, mbp2_nw_ymax, mbp2_nw_xmin]):
        print('    WARNING: could not determine PCell NWell extents for bridge')
        return

    # Y intersection (safe bridge range)
    bridge_ymin = max(mbp1_nw_ymin, mbp2_nw_ymin)
    bridge_ymax = min(mbp1_nw_ymax, mbp2_nw_ymax)
    if bridge_ymin >= bridge_ymax:
        print('    WARNING: NWell Y ranges do not overlap, cannot bridge')
        return

    # X range: from MBp1 NWell right to MBp2 NWell left
    bridge_x1 = mbp1_nw_xmax
    bridge_x2 = mbp2_nw_xmin

    if bridge_x1 >= bridge_x2:
        print(f'    NWell already overlaps (x1={bridge_x1} >= x2={bridge_x2}), no bridge needed')
        return

    cell.shapes(li_nw).insert(klayout.db.Box(bridge_x1, bridge_ymin, bridge_x2, bridge_ymax))
    print(f'    NWell bridge: [{bridge_x1}, {bridge_ymin}, {bridge_x2}, {bridge_ymax}] '
          f'({(bridge_x2-bridge_x1)/1000:.1f} x {(bridge_ymax-bridge_ymin)/1000:.1f} µm)')


# ═══════════════════════════════════════════════════
# Main assembly
# ═══════════════════════════════════════════════════

def main():
    placement, ties, routing = load_jsons()

    lib = pya.Library.library_by_name(LIB_NAME)
    if not lib:
        raise RuntimeError(f'Library {LIB_NAME} not found')

    layout = klayout.db.Layout(True)
    layout.dbu = 0.001  # nm
    top = layout.cell(layout.add_cell('ptat_vco'))

    # ── Layer indices ──
    li_m1 = layout.layer(*METAL1)
    li_m2 = layout.layer(*METAL2)
    li_m3 = layout.layer(*METAL3)
    li_v1 = layout.layer(*VIA1)
    li_v2 = layout.layer(*VIA2)
    li_m3_lbl = layout.layer(30, 25)   # LVS: metal3_text = labels(30, 25)
    li_m2_lbl = layout.layer(10, 25)   # LVS: metal2_text = labels(10, 25)

    # ═══ 1. Place PCells ═══
    print('\n  === Placing devices ===')
    instances = placement['instances']
    for inst_name, info in instances.items():
        dev_type = info['type']
        dev = DEVICES[dev_type]
        px = info['x_um']
        py = info['y_um']

        pcell_decl = lib.layout().pcell_declaration(dev['pcell'])
        pcell_id = layout.add_pcell_variant(lib, pcell_decl.id(), dev['params'])

        ox_nm = round((px - dev['ox']) * UM)
        oy_nm = round((py - dev['oy']) * UM)
        ox_nm = ((ox_nm + 2) // 5) * 5
        oy_nm = ((oy_nm + 2) // 5) * 5

        rot = dev.get('rotation', 0)
        top.insert(klayout.db.CellInstArray(
            pcell_id,
            klayout.db.Trans(rot, False, klayout.db.Point(ox_nm, oy_nm))
        ))
        print(f'    {inst_name:8s} ({dev_type:14s}) at ({px:7.2f}, {py:7.2f})')
    print(f'  Placed {len(instances)} devices')

    # Collect Via1 centers from ALL drawing phases for signal-route dedup.
    # Prevents duplicate Via1 at positions already drawn by gate contacts,
    # access points, or power drops.
    drawn_vias = set()

    # ═══ 1a. M1 S/D bus straps for ng>=2 devices ═══
    # IHP SG13G2 multi-finger PCells have isolated M1 strips per S/D finger.
    # The PCell does NOT internally connect same-type (S or D) strips.
    # Bus straps connect all source strips and all drain strips with M1 bars.
    #
    # Source bus (ABOVE device): connects intermediate source strips + S2.
    #   Skips S1 (strip 0) to avoid crossing D pin's m1_stub at strip 1.
    #   S1 connects to the net independently via its own access point.
    # Drain bus (BELOW device): connects D pin + intermediate drain strips.
    #   Stays within drain strip X range, avoiding S/S2 m1_stubs at edges.
    #
    # Geometry: 160nm-wide M1 bars with 200nm gap from strip edges (> M1.b=180nm).
    # Extends ~50-180nm beyond PCell bbox; well within placer's 700nm device gap.
    print('\n  === Drawing M1 S/D bus straps ===')
    BUS_W = M1_THIN   # 160nm — bus bar width (matches PCell M1 strip width)
    BUS_GAP = 200      # 200nm gap from strip edge to bus bar (> M1.b = 180nm)

    bus_count = 0
    for inst_name, info in instances.items():
        dev_type = info['type']
        sd = get_sd_strips(_device_lib, dev_type)
        if sd is None:
            continue

        dev = DEVICES[dev_type]
        pcell_x = s5(info['x_um'] - dev['ox'])
        pcell_y = s5(info['y_um'] - dev['oy'])

        src_strips = sd['source']
        drn_strips = sd['drain']
        strip_top = src_strips[0][3]  # All strips share same Y range
        strip_bot = src_strips[0][1]

        # Source bus above: skip S1 (strip 0), connect remaining source strips.
        # The bus crosses intermediate drain strips (no m1_stubs) but NOT
        # strip 1 (D pin with m1_stub extending upward).
        bus_src = src_strips[1:]  # source[1:] = strips 2, 4, 6, 8 for ng=8
        if len(bus_src) >= 2:
            by1 = pcell_y + strip_top + BUS_GAP
            by2 = by1 + BUS_W
            bx1 = pcell_x + bus_src[0][0]
            bx2 = pcell_x + bus_src[-1][2]
            # Horizontal bus bar
            top.shapes(li_m1).insert(klayout.db.Box(bx1, by1, bx2, by2))
            # Stubs connecting each source strip top to bus
            for strip in bus_src:
                top.shapes(li_m1).insert(klayout.db.Box(
                    pcell_x + strip[0], pcell_y + strip_top,
                    pcell_x + strip[2], by2))
            bus_count += 1

        # Drain bus below: connect all drain strips (D pin + intermediates).
        # Bus range = strip 1 to strip N-2, never reaches strip 0 or strip N,
        # so it avoids S/S2 m1_stubs (which may extend below for NMOS).
        if len(drn_strips) >= 2:
            by2 = pcell_y + strip_bot - BUS_GAP
            by1 = by2 - BUS_W
            bx1 = pcell_x + drn_strips[0][0]
            bx2 = pcell_x + drn_strips[-1][2]
            # Horizontal bus bar
            top.shapes(li_m1).insert(klayout.db.Box(bx1, by1, bx2, by2))
            # Stubs connecting each drain strip bottom to bus
            for strip in drn_strips:
                top.shapes(li_m1).insert(klayout.db.Box(
                    pcell_x + strip[0], by1,
                    pcell_x + strip[2], pcell_y + strip_bot))
            bus_count += 1

        n_src = len(bus_src) if len(bus_src) >= 2 else 0
        n_drn = len(drn_strips) if len(drn_strips) >= 2 else 0
        if n_src or n_drn:
            print(f'    {inst_name}: S bus {n_src} strips, D bus {n_drn} strips')
    print(f'  Drew {bus_count} M1 S/D bus straps')

    # ═══ 1b. Gate straps for ng=2 devices ═══
    # ng=2 PCells have 2 separate poly gate fingers (G1, G2).
    # PCells provide NO gate Cont — only S/D contacts.
    # We add: M1 strap (G1→G2) + Cont at BOTH G1 and G2 to connect poly→M1.
    print('\n  === Drawing gate straps (ng=2) ===')
    li_cont = layout.layer(*CONT)

    CONT_SZ = 160                        # Cont cut size (nm)
    CONT_ENC_M1_END = 50                 # M1.c1 endcap enclosure requirement
    STRAP_H = CONT_SZ                    # 160nm — M1.c=0 on top/bottom
    li_gatpoly = layout.layer(*GATPOLY)

    # Gate finger positions from device_lib.json (auto-extracted by probe_pcells_v2.py)
    NG2_GATE_DATA = {}
    for _dt in _device_lib:
        _gd = get_ng2_gate_data(_device_lib, _dt)
        if _gd is not None:
            NG2_GATE_DATA[_dt] = _gd

    strap_count = 0
    for inst_name, info in instances.items():
        dev_type = info['type']
        dev = DEVICES[dev_type]
        gdata = NG2_GATE_DATA.get(dev_type)
        if gdata is None:
            continue

        # PCell origin (nm, 5nm grid)
        pcell_x = round((info['x_um'] - dev['ox']) * UM)
        pcell_x = ((pcell_x + 2) // 5) * 5
        pcell_y = round((info['y_um'] - dev['oy']) * UM)
        pcell_y = ((pcell_y + 2) // 5) * 5

        # Absolute gate finger centres (nm, 5nm grid)
        g1_x = ((pcell_x + round(gdata['g1'] * UM) + 2) // 5) * 5
        g2_x = ((pcell_x + round(gdata['g2'] * UM) + 2) // 5) * 5
        # Poly bottom edge (absolute nm)
        poly_bot = ((pcell_y + round(gdata['poly_bot'] * UM) + 2) // 5) * 5

        hc = CONT_SZ // 2   # 80nm
        hs = STRAP_H // 2   # 80nm (strap H = Cont H = 160nm)

        # GatPoly extension for DRC-clean gate contacts (Cnt.d, Cnt.e, M1.b).
        # Extend poly down by GATE_POLY_EXT (230nm) below PCell poly_bot.
        ext_bot = poly_bot - GATE_POLY_EXT
        cont_cy = ext_bot + CNT_D_ENC + hc  # = poly_bot - 80

        # Draw GatPoly extensions at G1 and G2 (cap half-width for large-L)
        gi = _gate_info.get(dev_type)
        g1_hw = min(gi.finger_hws[0], 500) if gi else 250
        g2_hw = min(gi.finger_hws[1], 500) if gi else 250
        for gx, ghw in ((g1_x, g1_hw), (g2_x, g2_hw)):
            top.shapes(li_gatpoly).insert(klayout.db.Box(
                gx - ghw, ext_bot, gx + ghw, poly_bot))

        # M1 strap from G1 to G2, centred on cont_cy
        m1_enc = CONT_SZ // 2 + CONT_ENC_M1_END  # 80+50=130nm
        m1_x1 = g1_x - m1_enc
        m1_x2 = g2_x + m1_enc
        m1_y1 = cont_cy - hs
        m1_y2 = cont_cy + hs
        top.shapes(li_m1).insert(klayout.db.Box(m1_x1, m1_y1, m1_x2, m1_y2))

        # Cont at G1 and G2 (in extended poly zone)
        for gx in (g1_x, g2_x):
            top.shapes(li_cont).insert(klayout.db.Box(
                gx - hc, cont_cy - hc, gx + hc, cont_cy + hc))

        # m1_pin Via1+M2 is drawn by access point system (section 3).
        # Gate extras only draws Cont+M1+GatPoly ext.  M1 overlaps with access M1.

        print(f'    {inst_name}: M1 [{m1_x1},{m1_y1},{m1_x2},{m1_y2}], '
              f'Cont@G1({g1_x},{cont_cy}) G2({g2_x},{cont_cy})')
        strap_count += 1

    print(f'  Drew {strap_count} gate straps')

    # ═══ 1c. Gate contacts for ALL MOSFET devices ═══
    # IHP SG13G2 PCells provide NO Cont on gate poly — only S/D contacts.
    # Every gate pin needs an explicit Cont connecting poly→M1 in the gate
    # extension area (below active for all orientations here).
    # Gate access modes 'gate' and 'm1_pin' both need this.
    #
    # ng=1: single poly extension + Cont + M1 pad at G pin.
    # ng>=4: continuous GatPoly extension bar bridging ALL fingers on poly layer,
    #   then single Cont + M1 pad at finger[0] (same as ng=1).
    #   IHP ng>=4 PCells have SEPARATE gate poly rectangles per finger (380nm gap).
    #   We bridge them on GatPoly (in extension zone below Activ, no extra FETs).
    #   Gate connectivity on GatPoly, S/D connectivity on M1 — no layer conflict.
    print('\n  === Drawing gate contacts ===')

    from atk.route.access import _DEVICES as _ACC_DEV, get_access_mode
    from atk.pdk import M1_MIN_AREA

    gate_cont_count = 0
    gate_bridge_count = 0
    gate_cont_m1 = {}  # pin_key → [x1,y1,x2,y2] for fill checker
    hc = CONT_SZ // 2  # 80nm

    for inst_name, info in instances.items():
        dev_type = info['type']
        dev = DEVICES[dev_type]
        acc = _ACC_DEV.get(dev_type)
        if acc is None:
            continue

        # Skip ng=2 — already handled by gate strap code above
        ng = dev.get('params', {}).get('ng', 1)
        if ng == 2:
            continue

        # Only MOSFET gates need Cont
        if 'G' not in acc['pins']:
            continue

        mode = get_access_mode(dev_type, 'G')
        if mode not in ('gate', 'm1_pin'):
            continue

        g_rel_x, g_rel_y = acc['pins']['G']

        # PCell origin (nm)
        pcell_x = round((info['x_um'] - dev['ox']) * UM)
        pcell_x = ((pcell_x + 2) // 5) * 5
        pcell_y = round((info['y_um'] - dev['oy']) * UM)
        pcell_y = ((pcell_y + 2) // 5) * 5

        # Gate poly bottom Y (absolute nm) — same for all fingers
        poly_bot = ((pcell_y + round(g_rel_y * UM) + 2) // 5) * 5

        # GatPoly extension geometry
        ext_bot = poly_bot - GATE_POLY_EXT
        cy = ext_bot + CNT_D_ENC + hc  # = poly_bot - 80

        gi = _gate_info.get(dev_type)

        # ── ng>=4: bridge all gate poly fingers on GatPoly layer ──
        if ng >= 4 and gi and gi.ng >= 4:
            # One continuous GatPoly bar spanning finger[0]..finger[N-1]
            # in the extension zone [ext_bot, poly_bot] — below Activ,
            # so no extra transistors are formed.
            first_left = pcell_x + gi.finger_xs[0] - gi.finger_hws[0]
            last_right = pcell_x + gi.finger_xs[-1] + gi.finger_hws[-1]
            first_left = ((first_left + 2) // 5) * 5
            last_right = ((last_right + 2) // 5) * 5
            top.shapes(li_gatpoly).insert(klayout.db.Box(
                first_left, ext_bot, last_right, poly_bot))
            gate_bridge_count += 1
            print(f'    {inst_name}: GatPoly bridge ng={gi.ng}, '
                  f'X=[{first_left},{last_right}] Y=[{ext_bot},{poly_bot}]')

        # ── Single Cont + M1 pad at G pin (all ng values) ──
        gx = ((pcell_x + round(g_rel_x * UM) + 2) // 5) * 5

        # Draw GatPoly extension at contact finger.
        # Cap half-width: large-L ng=1 devices (e.g. pmos_mirror L=100µm)
        # have finger_hws ~50µm — a 100µm GatPoly bar would bridge nets.
        gate_hw = min(gi.finger_hws[0], 500) if gi else 250
        top.shapes(li_gatpoly).insert(klayout.db.Box(
            gx - gate_hw, ext_bot, gx + gate_hw, poly_bot))

        # Cont on gate poly (in extended zone)
        top.shapes(li_cont).insert(klayout.db.Box(
            gx - hc, cy - hc, gx + hc, cy + hc))

        # M1 pad covering Cont.  Via1+M2 drawn by access point system.
        # Top capped at poly_bot (avoid M1.b with S/D M1).
        # Extend downward to satisfy M1.d area ≥ 0.09 µm².
        m1_hw = hc + CONT_ENC_M1_END  # 130nm → width = 260nm
        m1_w = 2 * m1_hw
        m1_min_h = (M1_MIN_AREA + m1_w - 1) // m1_w
        m1_min_h = ((m1_min_h + 4) // 5) * 5  # 5nm grid
        m1_h = max(m1_min_h, poly_bot - (cy - hc))
        gc_m1 = [gx - m1_hw, poly_bot - m1_h, gx + m1_hw, poly_bot]
        top.shapes(li_m1).insert(klayout.db.Box(*gc_m1))
        gate_cont_m1[f'{inst_name}.G'] = gc_m1

        gate_cont_count += 1

    print(f'  Drew {gate_cont_count} gate contacts, {gate_bridge_count} poly bridges (ng>=4)')

    # ═══ 2. Draw tie cells from ties.json ═══
    print('\n  === Drawing ties ===')
    tie_layer_cache = {}
    for tie in ties.get('ties', []):
        tid = tie['id']
        for layer_key, rects in tie.get('layers', {}).items():
            ld = _parse_tie_layer(layer_key)
            if ld is None:
                print(f'    WARNING: unknown tie layer {layer_key}')
                continue
            if ld not in tie_layer_cache:
                tie_layer_cache[ld] = layout.layer(*ld)
            li = tie_layer_cache[ld]
            for rect in rects:
                draw_rect(top, li, rect)
    print(f'  Drew {len(ties.get("ties", []))} ties')

    # ── NWell extensions ──
    li_nw = layout.layer(*NWELL)
    for ext in ties.get('nwell_extensions', []):
        draw_rect(top, li_nw, ext['rect_nm'])
    print(f'  Drew {len(ties.get("nwell_extensions", []))} NWell extensions')

    # ── NWell bridge (MBp1 ↔ MBp2) ──
    _add_nwell_bridge(top, layout, placement)

    # ── NWell island fill (continuous NWell for shared-well groups) ──
    island_count = 0
    for island in placement.get('nwell_islands', []):
        bbox = island['bbox_um']
        x1 = int(bbox[0] * 1000)
        y1 = int(bbox[1] * 1000)
        x2 = int(bbox[2] * 1000)
        y2 = int(bbox[3] * 1000)
        top.shapes(li_nw).insert(klayout.db.Box(x1, y1, x2, y2))
        island_count += 1
        print(f'    NWell island {island["id"]}: '
              f'[{bbox[0]:.1f}, {bbox[1]:.1f}, {bbox[2]:.1f}, {bbox[3]:.1f}] µm '
              f'({island["net"]})')
    if island_count:
        print(f'  Drew {island_count} NWell island fills')

    # ═══ 3. Draw access points ═══
    print('\n  === Drawing access points ===')

    # Build set of via_stack pins (they skip access point drawing)
    via_stack_pins = set()
    for drop in routing.get('power', {}).get('drops', []):
        if drop['type'] == 'via_stack':
            via_stack_pins.add(f"{drop['inst']}.{drop['pin']}")

    # drawn_vias already contains gate-contact Via1 positions from section 1c.
    # Now add access-point Via1 positions.
    gate_via_count = len(drawn_vias)

    ap_count = 0
    for key, ap in routing.get('access_points', {}).items():
        is_via_stack = key in via_stack_pins
        vp = ap.get('via_pad')
        skip_m1 = ap.get('mode') == 'gate_no_m1'
        if vp and not is_via_stack:
            if 'via1' in vp:
                draw_rect(top, li_v1, vp['via1'])
                v = vp['via1']
                drawn_vias.add(((v[0] + v[2]) // 2, (v[1] + v[3]) // 2))
            if 'm1' in vp and not skip_m1:
                draw_rect(top, li_m1, vp['m1'])
            if 'm2' in vp:
                draw_rect(top, li_m2, vp['m2'])
        # Always draw m1_stub — via_stack pins need it to bridge
        # ptap/ntap tie M1 to PCell M1 strip
        if ap.get('m1_stub') and not skip_m1:
            draw_rect(top, li_m1, ap['m1_stub'])
        if ap.get('m2_stub') and not is_via_stack:
            draw_rect(top, li_m2, ap['m2_stub'])
        ap_count += 1
    print(f'  Drew {ap_count} access points ({len(drawn_vias)} via1 positions tracked)')

    # ═══ 4. Draw power rails + drops ═══
    print('\n  === Drawing power ===')

    # M3 horizontal rails
    for rail_id, rail in routing.get('power', {}).get('rails', {}).items():
        hbar(top, li_m3, rail['x1'], rail['x2'], rail['y'], rail['width'])
        net_label = rail.get('net', rail_id)
        print(f'    Rail {rail_id:12s} ({net_label:8s}): y={rail["y"]/1000:.1f}µm')

    # Build rail data for M3 crossing detection
    all_rails = routing.get('power', {}).get('rails', {})

    # Pre-collect M2 signal segments for bridge conflict checking
    m2_signal_segs = []
    for _sn, _sr in routing.get('signal_routes', {}).items():
        for seg in _sr.get('segments', []):
            if len(seg) >= 5 and seg[4] == M2_LYR:
                m2_signal_segs.append(seg[:4])  # x1,y1,x2,y2

    # Power drops
    drop_count = 0
    for drop in routing.get('power', {}).get('drops', []):
        dtype = drop['type']
        if dtype == 'via_access':
            # M2 vbar from via2 toward pin
            vb = drop['m2_vbar']
            vbar(top, li_m2, vb[0], vb[1], vb[3], M2_SIG_W)
            # M2 jog connecting vbar to access pad — use VIA1_PAD width
            # to match M2 pad height and avoid M2.b notch violations
            if 'm2_jog' in drop:
                jog = drop['m2_jog']
                hbar(top, li_m2, jog[0], jog[2], jog[1], VIA1_PAD)
            # M2 fill: bridge the gap between vbar right edge and pad left edge
            # (vbar at offset X, pad centered on pin — 30nm gap without fill)
            _fill_vbar_to_pad(top, li_m2, vb, drop, routing)
            # Via2 at rail
            v2 = drop['via2_pos']
            via2(top, li_v2, li_m2, li_m3, v2[0], v2[1])
        elif dtype == 'via_stack':
            drop_net = drop['net']
            # Find nearest same-net rail (multi-rail support)
            target_rail = None
            pin_y = drop['via2_pos'][1]
            best_dist = float('inf')
            for _rid, _rl in all_rails.items():
                if _rl.get('net', _rid) != drop_net:
                    continue
                d = abs(_rl['y'] - pin_y)
                if d < best_dist:
                    best_dist = d
                    target_rail = _rl
            # Via1 at pin
            v1 = drop['via1_pos']
            via1(top, li_v1, li_m1, li_m2, v1[0], v1[1])

            if 'm3_vbar' not in drop or target_rail is None:
                # No M3 connection needed, just via2 at pin
                v2 = drop['via2_pos']
                via2(top, li_v2, li_m2, li_m3, v2[0], v2[1])
            else:
                m3v = drop['m3_vbar']
                pin_x = m3v[0]
                pin_y = drop['via2_pos'][1]
                rail_y = target_rail['y']
                vbar_y1 = min(pin_y, rail_y)
                vbar_y2 = max(pin_y, rail_y)

                # Collect exclusion zones (other nets' M3 rails)
                # Clearance = rail half-width + M3.b spacing + VIA2 pad half
                # so bridge via2 M3 pad doesn't violate spacing with rail
                hp_v2 = VIA2_PAD // 2
                excl = []
                for rn, rl in all_rails.items():
                    if rl.get('net', rn) == drop_net:
                        continue
                    rh = rl['width'] // 2
                    ry_lo = rl['y'] - rh - M3_MIN_S - hp_v2
                    ry_hi = rl['y'] + rh + M3_MIN_S + hp_v2
                    if ry_lo < vbar_y2 and ry_hi > vbar_y1:
                        excl.append((ry_lo, ry_hi))
                excl.sort()

                if not excl:
                    # No crossing — draw via2 at pin + M3 vbar
                    v2 = drop['via2_pos']
                    via2(top, li_v2, li_m2, li_m3, v2[0], v2[1])
                    vbar(top, li_m3, pin_x, pin_y, rail_y, VIA2_PAD)
                else:
                    # M3 vbar crosses rails — draw M3 segments with gaps,
                    # bridge gaps with M2 underpass (via2 at gap edges)
                    # Pin via2 only if pin is NOT inside an exclusion zone
                    pin_in_excl = any(e[0] <= pin_y <= e[1] for e in excl)
                    if not pin_in_excl:
                        via2(top, li_v2, li_m2, li_m3, pin_x, pin_y)

                    # Draw M3 segments in gaps between exclusion zones
                    seg_y1 = vbar_y1
                    gap_entries = []
                    for ey1, ey2 in excl:
                        if ey1 > seg_y1:
                            vbar(top, li_m3, pin_x, seg_y1, ey1, VIA2_PAD)
                        gap_entries.append((max(seg_y1, ey1), ey2))
                        seg_y1 = max(seg_y1, ey2)
                    if seg_y1 < vbar_y2:
                        vbar(top, li_m3, pin_x, seg_y1, vbar_y2, VIA2_PAD)

                    # Bridge each gap with M2 underpass
                    # Check M2 signal conflicts and shift bridge X if needed
                    hp_m2 = VIA2_PAD // 2
                    for gy1, gy2 in gap_entries:
                        # Determine if each gap edge is inside an excl zone
                        # (i.e. M3 pad at that point would short to a rail)
                        gy1_in_excl = any(
                            (rl['y'] - rl['width']//2) < gy1 + hp_m2
                            and (rl['y'] + rl['width']//2) > gy1 - hp_m2
                            for rn, rl in all_rails.items()
                            if rl.get('net', rn) != drop_net
                        )
                        gy2_in_excl = any(
                            (rl['y'] - rl['width']//2) < gy2 + hp_m2
                            and (rl['y'] + rl['width']//2) > gy2 - hp_m2
                            for rn, rl in all_rails.items()
                            if rl.get('net', rn) != drop_net
                        )

                        # Check if M2 bridge at pin_x conflicts with signals
                        bridge_x = pin_x
                        has_conflict = False
                        for sx1, sy1, sx2, sy2 in m2_signal_segs:
                            sw = M2_SIG_W // 2
                            if sx1 == sx2:  # M2 vertical
                                if ((sx1 - sw) < bridge_x + hp_m2
                                        and (sx1 + sw) > bridge_x - hp_m2):
                                    slo, shi = min(sy1, sy2), max(sy1, sy2)
                                    if slo < gy2 and shi > gy1:
                                        has_conflict = True
                                        break
                            elif sy1 == sy2:  # M2 horizontal
                                if gy1 < sy1 < gy2:
                                    slo_x = min(sx1, sx2)
                                    shi_x = max(sx1, sx2)
                                    if ((slo_x - sw) < bridge_x + hp_m2
                                            and (shi_x + sw) > bridge_x - hp_m2):
                                        has_conflict = True
                                        break

                        if has_conflict:
                            # Shift bridge X left by 1600nm to clear conflict
                            bridge_x = pin_x - 1600
                            print(f'    M2 bridge shifted x={pin_x}->{bridge_x} '
                                  f'for gap y={gy1}-{gy2}')

                        # Draw via2 at gap edges — skip M3 pad if edge
                        # is inside another net's rail (would short)
                        if not gy1_in_excl:
                            via2(top, li_v2, li_m2, li_m3, bridge_x, gy1)
                        if not gy2_in_excl:
                            via2(top, li_v2, li_m2, li_m3, bridge_x, gy2)

                        vbar(top, li_m2, bridge_x, gy1, gy2, VIA2_PAD)

                        # If bridge_x shifted, add M3 jogs to connect back
                        if bridge_x != pin_x:
                            # Only draw M3 jog if that edge is not in excl
                            if not gy1_in_excl:
                                hbar(top, li_m3, min(bridge_x, pin_x),
                                     max(bridge_x, pin_x), gy1, VIA2_PAD)
                            if not gy2_in_excl:
                                hbar(top, li_m3, min(bridge_x, pin_x),
                                     max(bridge_x, pin_x), gy2, VIA2_PAD)
        drop_count += 1
    print(f'  Drew {drop_count} power drops')

    # ── Multi-rail bridges (connect same-net M3 rails via M2 underpass) ──
    _draw_rail_bridges(top, li_m2, li_v2, li_m3, all_rails, m2_signal_segs)

    # ═══ 5. Draw signal routing ═══
    print('\n  === Drawing signal routes ===')

    # Pre-routes
    for net_name, route in routing.get('pre_routes', {}).items():
        segs = route.get('segments', [])
        draw_segments(top, li_m1, li_m2, li_v1, segs, M2_SIG_W,
                      drawn_vias=drawn_vias)
        print(f'    Pre-route {net_name}: {len(segs)} segments')

    # Signal routes (drawn_vias prevents duplicate Via1 at access point positions)
    total_segs = 0
    via1_before = len(drawn_vias)
    total_via1_segs = 0
    for net_name, route in routing.get('signal_routes', {}).items():
        segs = route.get('segments', [])
        total_via1_segs += sum(1 for s in segs if s[4] == -1)
        draw_segments(top, li_m1, li_m2, li_v1, segs, M1_SIG_W,
                      drawn_vias=drawn_vias)
        total_segs += len(segs)
    new_vias = len(drawn_vias) - via1_before
    skipped_vias = total_via1_segs - new_vias
    print(f'  Drew {len(routing.get("signal_routes", {}))} signal nets, '
          f'{total_segs} segments ({new_vias} new vias, '
          f'{skipped_vias} deduped)')

    # Fill M1 corner notches at routing via bends
    _fill_via_m1_corners(top, li_m1, routing, gate_cont_m1)

    # Fill M2 gaps between routing vias and access point M2 pads
    _fill_via_ap_m2_gaps(top, li_m2, routing)

    # ── M2 collision check: signal routes vs power M2 pads ──
    _check_m2_power_signal_collision(routing)

    # ═══ 6. Pin labels for LVS ═══
    print('\n  === Adding pin labels ===')

    # Power labels on M3 rails
    rails = routing.get('power', {}).get('rails', {})
    for rail_id, rail in rails.items():
        label = rail.get('net', rail_id)  # Use net name, not rail_id
        mid_x = (rail['x1'] + rail['x2']) // 2
        top.shapes(li_m3_lbl).insert(klayout.db.Text(
            label, klayout.db.Trans(klayout.db.Point(mid_x, rail['y']))))

    # Signal labels on M1 (8,25) and M2 (10,25) for every signal net.
    # LVS needs labels to name extracted nets; unlabelled nets become $N.
    li_m1_lbl = layout.layer(8, 25)
    sig_label_count = 0
    # Build pin→net map for 0-segment net label placement
    _ap_data = routing.get('access_points', {})

    for net_name, route in routing.get('signal_routes', {}).items():
        segs = route.get('segments', [])
        if not segs:
            # 0-segment net (same-cell connection): place label on M2 at
            # first access point that has a via_pad (Via1 M2 pad).
            # Without a label, KLayout LVS cannot name the extracted net.
            pins = route.get('pins', [])
            labeled = False
            for pin_key in pins:
                ap = _ap_data.get(pin_key)
                if ap and ap.get('via_pad') and 'm2' in ap['via_pad']:
                    vp = ap['via_pad']['m2']
                    mx = (vp[0] + vp[2]) // 2
                    my = (vp[1] + vp[3]) // 2
                    top.shapes(li_m2_lbl).insert(klayout.db.Text(
                        net_name, klayout.db.Trans(klayout.db.Point(mx, my))))
                    sig_label_count += 1
                    labeled = True
                    break
            if not labeled and pins:
                # Fallback: use access point position directly
                ap = _ap_data.get(pins[0])
                if ap:
                    top.shapes(li_m2_lbl).insert(klayout.db.Text(
                        net_name, klayout.db.Trans(
                            klayout.db.Point(ap['x'], ap['y']))))
                    sig_label_count += 1
            continue
        # Prefer M2 segment for label (layer=1), fallback to M1 (layer=0)
        m2_seg = next((s for s in segs if s[4] == 1), None)
        m1_seg = next((s for s in segs if s[4] == 0), None)
        if m2_seg:
            mx = (m2_seg[0] + m2_seg[2]) // 2
            my = (m2_seg[1] + m2_seg[3]) // 2
            top.shapes(li_m2_lbl).insert(klayout.db.Text(
                net_name, klayout.db.Trans(klayout.db.Point(mx, my))))
            sig_label_count += 1
        elif m1_seg:
            mx = (m1_seg[0] + m1_seg[2]) // 2
            my = (m1_seg[1] + m1_seg[3]) // 2
            top.shapes(li_m1_lbl).insert(klayout.db.Text(
                net_name, klayout.db.Trans(klayout.db.Point(mx, my))))
            sig_label_count += 1
    # Pre-routes too
    for net_name, route in routing.get('pre_routes', {}).items():
        segs = route.get('segments', [])
        if not segs:
            continue
        m2_seg = next((s for s in segs if s[4] == 1), None)
        if m2_seg:
            mx = (m2_seg[0] + m2_seg[2]) // 2
            my = (m2_seg[1] + m2_seg[3]) // 2
            top.shapes(li_m2_lbl).insert(klayout.db.Text(
                net_name, klayout.db.Trans(klayout.db.Point(mx, my))))
            sig_label_count += 1

    print(f'  Added pin labels: vdd/vdd_vco/gnd (M3), {sig_label_count} signal nets')

    # ═══ Summary ═══
    bb = top.bbox()
    w_um = bb.width() * 0.001
    h_um = bb.height() * 0.001
    area_um2 = w_um * h_um
    print(f'\n  Bounding box: {w_um:.1f} x {h_um:.1f} µm = {area_um2:.0f} µm²')
    print(f'  Tile 1×2: 202.1 × 313.7 µm = 63,399 µm²')
    print(f'  Utilization: {area_um2/63399*100:.1f}%')

    # ═══ Write GDS ═══
    default_gds = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output', 'ptat_vco.gds')
    output = os.environ.get('GDS_OUTPUT', default_gds)
    layout.write(output)
    print(f'\n  Written to {output}')


if __name__ == '__main__':
    main()
