"""Single source of truth for project file paths.

All scripts that read placement.json, netlist.json, ties.json, routing.json
MUST import paths from here to prevent single-source-of-truth violations.

    LAYOUT_DIR  — canonical location for placement.json, netlist.json
    WORK_DIR    — intermediate build outputs (ties.json, routing.json, GDS)
"""
import os

LAYOUT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK_DIR = os.path.join(LAYOUT_DIR, 'output')

# ── Canonical file paths ──
PLACEMENT_JSON = os.path.join(LAYOUT_DIR, 'placement.json')
NETLIST_JSON = os.path.join(LAYOUT_DIR, 'netlist.json')
DEVICE_LIB_JSON = os.path.join(LAYOUT_DIR, 'atk', 'data', 'device_lib.json')
DEVICE_LIB_MAGIC_JSON = os.path.join(LAYOUT_DIR, 'atk', 'data', 'device_lib_magic.json')

# Work dir outputs (generated by solvers, consumed by assembler)
TIES_JSON = os.path.join(WORK_DIR, 'ties.json')
ROUTING_JSON = os.path.join(WORK_DIR, 'routing.json')
OUTPUT_GDS = os.path.join(WORK_DIR, 'soilz.gds')
